"""Property-based tests for the hit-disposition invariant.

The property under test is exactly the one AD A.7a states:

    for every ladder trace, either the envelope records every retrieved id at some depth
    or in a withheld record, or construction fails.

There is no third outcome, and in particular there is no outcome in which a response is
returned having quietly lost a hit. The strategies below generate the ladder traces -
arbitrary hit sets accumulated across arbitrary rungs, arbitrary disclosure decisions and
a deliberately unreliable cap that sometimes forgets to file its record.
"""

from __future__ import annotations

from collections.abc import Mapping

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from mailweave.envelope import (
    Affordance,
    DispositionLedger,
    EnvelopeBuilder,
    Outcome,
    RungId,
    Sufficiency,
    ToolName,
    WithheldCap,
)
from mailweave.envelope.disposition import FetchedIds
from mailweave.errors import DispositionInvariantError
from tests.fixtures import envelope_kit as kit

message_ids = st.from_regex(r"[a-z0-9]{1,8}", fullmatch=True)
id_sets = st.lists(message_ids, unique=True, min_size=0, max_size=12)
rungs = st.sampled_from([RungId.L0, RungId.L1, RungId.L2, RungId.L3, RungId.L5, RungId.LR])
#: Threads are drawn from their own alphabet, unrelated to the message-id alphabet, so no
#: example can pass by an id and its thread happening to coincide (R-DISC-009).
thread_ids = st.from_regex(r"T[A-Z]{1,4}", fullmatch=True)


def _observed_threads(hits: list[str], choices: list[str]) -> dict[str, str]:
    """Assign each hit a thread, cycling through independently generated thread ids.

    Ids and threads are generated by separate strategies and paired here, so which thread
    a message was observed in is never a function of the message id. That is what makes
    the assertions below able to see a record that took its thread from anywhere else.
    """
    return {mid: choices[index % len(choices)] for index, mid in enumerate(hits)}


def _load_ledger(
    ledger: DispositionLedger,
    hits: list[str],
    pages: list[RungId],
    threads: Mapping[str, str] | None = None,
) -> None:
    """Spread `hits` across several executed queries, as a real ladder would.

    `threads` is the `threadId` each page carried beside its ids. It is passed through to
    the observation rather than to `note_withheld`, because the thread a withheld record is
    charged against is read off the observation (R-DISC-009).
    """
    if not hits:
        return
    per_id = dict(threads or {})

    def page(ids: list[str]) -> FetchedIds:
        return kit.fetched(ids, thread_ids={mid: per_id[mid] for mid in ids} if per_id else None)

    chunk = max(1, len(hits) // max(1, len(pages)))
    for index, rung in enumerate(pages):
        piece = hits[index * chunk : (index + 1) * chunk]
        if not piece:
            continue
        ledger.record_list_page(page(piece), rung=rung, query=f"probe-{index}")
    remaining = hits[len(pages) * chunk :]
    if remaining:
        ledger.record_list_page(
            page(remaining), rung=pages[0] if pages else RungId.L1, query="probe-tail"
        )


@settings(max_examples=200)
@given(
    hits=id_sets,
    disclose_flags=st.lists(st.booleans(), min_size=0, max_size=12),
    note_flags=st.lists(st.booleans(), min_size=0, max_size=12),
    extra_disclosed=id_sets,
    pages=st.lists(rungs, min_size=1, max_size=4),
    thread_choices=st.lists(thread_ids, min_size=1, max_size=12),
)
def test_certification_either_accounts_for_every_hit_or_raises(
    hits: list[str],
    disclose_flags: list[bool],
    note_flags: list[bool],
    extra_disclosed: list[str],
    pages: list[RungId],
    thread_choices: list[str],
) -> None:
    ledger = DispositionLedger()
    observed = _observed_threads(hits, thread_choices)
    _load_ledger(ledger, hits, pages, observed)

    disclosed = {mid for mid, keep in zip(hits, disclose_flags, strict=False) if keep}
    # Messages that were never hits may also be disclosed (context, parents, children).
    disclosed |= set(extra_disclosed) - set(hits)

    dropped = [mid for mid in hits if mid not in disclosed]
    forgotten = set()
    for index, mid in enumerate(dropped):
        remembered = note_flags[index] if index < len(note_flags) else True
        if remembered:
            ledger.note_withheld(
                message_id=mid,
                cap=WithheldCap.MAX_HIT_THREADS,
                why="cap fired",
                affordance=Affordance(tool=ToolName.THREAD_MAP, args={"thread_id": "t1"}),
            )
        else:
            forgotten.add(mid)

    if forgotten:
        with pytest.raises(DispositionInvariantError) as failure:
            ledger.certify(disclosed)
        # The failure names what was lost, so a reviewer can act on it.
        assert any(mid in str(failure.value) for mid in forgotten)
        return

    certificate = ledger.certify(disclosed)
    assert certificate.withheld_ids == set(hits) - disclosed
    assert certificate.hit_count == len(set(hits))
    assert certificate.disclosed_hits + len(certificate.withheld) == certificate.hit_count
    # R-DISC-009: threads are drawn independently of ids, so a record that carried the
    # caller's idea of the thread rather than the observation's would disagree here on
    # any example where the two differ - which is most of them.
    assert {record.id: record.thread_id for record in certificate.withheld} == {
        mid: observed[mid] for mid in certificate.withheld_ids
    }


@settings(max_examples=100)
@given(
    hits=st.lists(message_ids, unique=True, min_size=1, max_size=8),
    disclose_flags=st.lists(st.booleans(), min_size=0, max_size=8),
    note_flags=st.lists(st.booleans(), min_size=0, max_size=8),
    unreported_total=st.integers(min_value=0, max_value=4),
)
def test_a_built_envelope_always_contains_every_hit(
    hits: list[str],
    disclose_flags: list[bool],
    note_flags: list[bool],
    unreported_total: int,
) -> None:
    """`H subset-of R` on every envelope that is successfully built."""
    ledger = DispositionLedger()
    disclosed = [mid for mid, keep in zip(hits, disclose_flags, strict=False) if keep]
    dropped = [mid for mid in hits if mid not in disclosed]
    # The source below is thread "t1" and the messages that will be withheld belong to a
    # different thread, so the two pages are recorded separately - which is also how a real
    # ladder sees them, one `messages.list` response per query, each carrying its own
    # `threadId` per item.
    if disclosed:
        ledger.record_list_page(
            kit.fetched(disclosed, thread="t1"), rung=RungId.L1, query="from:amy launch"
        )
    if dropped:
        ledger.record_list_page(
            kit.fetched(dropped, thread="t2"), rung=RungId.L1, query="from:amy launch (2)"
        )

    forgot_one = False
    for index, mid in enumerate(dropped):
        if index < len(note_flags) and not note_flags[index]:
            forgot_one = True
            continue
        ledger.note_withheld(
            message_id=mid,
            cap=WithheldCap.DISCLOSED_TOKEN_CEILING,
            why="ceiling reached after the degradation ladder",
            affordance=Affordance(tool=ToolName.THREAD_MAP, args={"thread_id": "t2"}),
        )

    builder = EnvelopeBuilder(ledger, asked_for=kit.asked_for())
    nonce = builder.fence_nonce
    rows = [kit.row(mid, "t1", position, nonce=nonce) for position, mid in enumerate(disclosed)]
    builder.add_source(kit.source("t1", rows, stated_total=len(rows) + unreported_total))
    builder.add_affordance(kit.thread_affordance("t1"))

    def build() -> object:
        return builder.build(
            outcome=Outcome.ANSWERED if disclosed else Outcome.INCONCLUSIVE,
            rungs=(RungId.L1,),
            sufficiency=Sufficiency.AMBIGUOUS,
            counters=kit.counters(),
            empty_diagnosis=kit.empty_diagnosis_complete(),
        )

    if forgot_one:
        with pytest.raises(DispositionInvariantError):
            build()
        return

    envelope = build()
    assert set(hits) <= envelope.represented_ids  # type: ignore[attr-defined]
    # R-DISC-009: every withheld record names the thread its id was observed in, which is
    # "t2" here - never "t1", the thread of the source that would benefit from the claim.
    assert {r.thread_id for r in envelope.withheld} <= {"t2"}  # type: ignore[attr-defined]
    assert envelope.disclosed_ids.isdisjoint(envelope.withheld_ids)  # type: ignore[attr-defined]
    assert envelope.partial == bool(  # type: ignore[attr-defined]
        envelope.withheld or unreported_total  # type: ignore[attr-defined]
    )


@settings(max_examples=200)
@given(
    hits=st.lists(message_ids, unique=True, min_size=1, max_size=6),
    observed_choices=st.lists(thread_ids, min_size=1, max_size=4),
    placement_choices=st.lists(thread_ids, min_size=1, max_size=4),
    move_flags=st.lists(st.booleans(), min_size=0, max_size=6),
)
def test_a_disclosed_row_may_only_sit_in_the_thread_it_was_observed_in(
    hits: list[str],
    observed_choices: list[str],
    placement_choices: list[str],
    move_flags: list[bool],
) -> None:
    """R-DISC-011: the disclosed twin of the property above.

    Two thread assignments are drawn from **two independently generated lists**: the one
    the observation recorded, and the one the response places the row under. Neither is a
    function of the other or of the message id, so an implementation that took the source's
    word for it - or that "checked" a row against a value copied from the same source -
    agrees with itself on every example and disagrees with this test on most of them.

    The expectation is stated as the relation, not as a count: construction succeeds
    exactly when every disclosed id sits in the thread its observation named.
    """
    observed = {mid: observed_choices[i % len(observed_choices)] for i, mid in enumerate(hits)}
    # Per id, either the response places the row where the observation put it, or it places
    # it under a thread drawn from a **separate** list. Without the flag the two lists
    # almost never agree and the "builds cleanly" branch is reached on well under 1% of
    # examples, so the property would be a detector test wearing a property test's clothes.
    # The flag is not what the assertion reads - the assertion reads the relation - so an
    # independently drawn thread that happens to coincide is handled as agreement, which is
    # a case a flag-driven expectation would get wrong.
    placed = {
        mid: (
            placement_choices[index % len(placement_choices)]
            if index < len(move_flags) and move_flags[index]
            else observed[mid]
        )
        for index, mid in enumerate(hits)
    }

    ledger = DispositionLedger()
    ledger.record_list_page(
        kit.fetched(hits, thread_ids=observed), rung=RungId.L1, query="from:amy launch"
    )

    builder = EnvelopeBuilder(ledger, asked_for=kit.asked_for())
    nonce = builder.fence_nonce
    by_thread: dict[str, list[str]] = {}
    for mid in hits:
        by_thread.setdefault(placed[mid], []).append(mid)
    for thread, members in by_thread.items():
        builder.add_source(
            kit.source(
                thread,
                [
                    kit.row(mid, thread, position, nonce=nonce)
                    for position, mid in enumerate(members)
                ],
            )
        )
        builder.add_affordance(kit.thread_affordance(thread))

    def build() -> object:
        return builder.build(
            outcome=Outcome.ANSWERED,
            rungs=(RungId.L1,),
            sufficiency=Sufficiency.SUFFICIENT,
            counters=kit.counters(),
        )

    borrowed = {mid for mid in hits if observed[mid] != placed[mid]}
    if borrowed:
        with pytest.raises(DispositionInvariantError) as failure:
            build()
        assert any(mid in str(failure.value) for mid in borrowed)
        return

    envelope = build()
    assert envelope.disclosed_ids == set(hits)  # type: ignore[attr-defined]
    for source in envelope.sources:  # type: ignore[attr-defined]
        for message_id in source.disclosed_ids:
            assert observed[message_id] == source.thread_id
