"""Query analysis (WS-04, AD A.2 step 1 / A.6 / A.6a / A.8a's lexicon).

Deterministic and model-free. Nothing in this package imports a model, embeds anything, or
consults corpus frequency; `generative_llm_calls = 0` is a hard constant (AD D.8) and the
CI import sweep is what enforces it, but the design reason it is easy to enforce here is
that every decision below is a table.
"""

from mailweave.query.analysis import (
    ANSWER_TYPE_BY_INTERROGATIVE,
    DATE_WINDOW_CONSTRAINT,
    DECISION_VERBS,
    INTERROGATIVE_PATTERNS,
    PHRASE_CONSTRAINT,
    RELAXATION_ORDER,
    RISK_FACTORS,
    STOPWORDS,
    TERMS_CONSTRAINT,
    UNPARSED_SYNTAX_CONSTRAINT,
    AnswerType,
    ConfidenceTier,
    Constraint,
    Interrogative,
    ParsedQuery,
    Participant,
    RiskFactor,
    analyse,
    carries_nothing_to_select_by,
    classify_interrogative,
    content_tokens,
    dropped_declarations,
    enforced_declarations,
    fold,
    matches_answer_type,
    normalise_participant,
    region_constraint_names,
    region_declarations_of,
    search_region_of,
    selects_something,
)
from mailweave.query.identifiers import (
    PUBLISHED_NON_IDENTIFIER_WORDS,
    IdentifierKind,
    StructuredIdentifier,
    classify_identifier,
)
from mailweave.query.operators import (
    GROUP_CLOSERS,
    GROUP_OPENERS,
    KIND_BY_OPERATOR,
    UNPARSED_SYNTAX,
    OperatorKind,
    OperatorName,
    ParsedOperator,
    Token,
    TokenRole,
    declares_the_search_region,
    operator_of,
    tokenise,
)
from mailweave.query.timepolicy import (
    FALLBACK_ZONE,
    RELATIVE_EXPRESSIONS,
    RelativeMatch,
    TimeWindow,
    find_relative_expression,
    reference_zone,
    resolve_relative,
    widening_declaration,
    window_from_operators,
)

__all__ = [
    "ANSWER_TYPE_BY_INTERROGATIVE",
    "DATE_WINDOW_CONSTRAINT",
    "DECISION_VERBS",
    "FALLBACK_ZONE",
    "GROUP_CLOSERS",
    "GROUP_OPENERS",
    "INTERROGATIVE_PATTERNS",
    "KIND_BY_OPERATOR",
    "PHRASE_CONSTRAINT",
    "PUBLISHED_NON_IDENTIFIER_WORDS",
    "RELATIVE_EXPRESSIONS",
    "RELAXATION_ORDER",
    "RISK_FACTORS",
    "STOPWORDS",
    "TERMS_CONSTRAINT",
    "UNPARSED_SYNTAX",
    "UNPARSED_SYNTAX_CONSTRAINT",
    "AnswerType",
    "ConfidenceTier",
    "Constraint",
    "IdentifierKind",
    "Interrogative",
    "OperatorKind",
    "OperatorName",
    "ParsedOperator",
    "ParsedQuery",
    "Participant",
    "RelativeMatch",
    "RiskFactor",
    "StructuredIdentifier",
    "TimeWindow",
    "Token",
    "TokenRole",
    "analyse",
    "carries_nothing_to_select_by",
    "classify_identifier",
    "classify_interrogative",
    "content_tokens",
    "declares_the_search_region",
    "dropped_declarations",
    "enforced_declarations",
    "find_relative_expression",
    "fold",
    "matches_answer_type",
    "normalise_participant",
    "operator_of",
    "reference_zone",
    "region_constraint_names",
    "region_declarations_of",
    "resolve_relative",
    "search_region_of",
    "selects_something",
    "tokenise",
    "widening_declaration",
    "window_from_operators",
]
