"""Response envelope and partiality metadata (WS-03)."""

from mailweave.envelope.builder import EnvelopeBuilder
from mailweave.envelope.disposition import (
    DispositionCertificate,
    DispositionLedger,
    FetchedIds,
    HitOrigin,
    ObservedEndpoint,
    disclosure_digest,
)
from mailweave.envelope.fence import FenceViolation, fence, is_fenced, mint_nonce, unfence
from mailweave.envelope.measure import degradation_artifacts, measure_tokens
from mailweave.envelope.reasons import Reason, ReasonKind, RungId
from mailweave.envelope.response import Envelope
from mailweave.envelope.vocab import (
    BLOCKING_NOT_TRIED,
    BudgetCapName,
    Completeness,
    ContentSource,
    Depth,
    EmptyDiagnosisStatus,
    Linkage,
    NotTriedWhy,
    Outcome,
    ParticipantRole,
    Role,
    Sufficiency,
    ToolName,
    Trust,
    WithheldCap,
)
from mailweave.envelope.wire import (
    Affordance,
    AskedFor,
    AttachmentMetadata,
    BudgetBlock,
    BudgetClamp,
    Ceiling,
    CollapsedRun,
    Content,
    Counters,
    DroppedConstraint,
    EmptyDiagnosis,
    ErrorEntry,
    MailboxProvenance,
    MessageRow,
    NotIncludedSource,
    NotTriedEntry,
    ParsedQuerySummary,
    PoolBlock,
    RetrievalReport,
    ScanScopeEntry,
    Score,
    Shortlist,
    Source,
    ThreadParticipant,
    ThreadStructureReport,
    WithheldRecord,
)

__all__ = [
    "BLOCKING_NOT_TRIED",
    "Affordance",
    "AskedFor",
    "AttachmentMetadata",
    "BudgetBlock",
    "BudgetCapName",
    "BudgetClamp",
    "Ceiling",
    "CollapsedRun",
    "Completeness",
    "Content",
    "ContentSource",
    "Counters",
    "Depth",
    "DispositionCertificate",
    "DispositionLedger",
    "DroppedConstraint",
    "EmptyDiagnosis",
    "EmptyDiagnosisStatus",
    "Envelope",
    "EnvelopeBuilder",
    "ErrorEntry",
    "FenceViolation",
    "FetchedIds",
    "HitOrigin",
    "Linkage",
    "MailboxProvenance",
    "MessageRow",
    "NotIncludedSource",
    "NotTriedEntry",
    "NotTriedWhy",
    "ObservedEndpoint",
    "Outcome",
    "ParsedQuerySummary",
    "ParticipantRole",
    "PoolBlock",
    "Reason",
    "ReasonKind",
    "RetrievalReport",
    "Role",
    "RungId",
    "ScanScopeEntry",
    "Score",
    "Shortlist",
    "Source",
    "Sufficiency",
    "ThreadParticipant",
    "ThreadStructureReport",
    "ToolName",
    "Trust",
    "WithheldCap",
    "WithheldRecord",
    "degradation_artifacts",
    "disclosure_digest",
    "fence",
    "is_fenced",
    "measure_tokens",
    "mint_nonce",
    "unfence",
]
